<?php
//Name: HO YI VON
//Student ID : 23WMR14542
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class MoviesTableSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('movies')->insert([
            [
                'title'        => 'The Super Mario Bros. Movie 2',
                'genre'        => 'Animation',
                'director'     => 'Aaron Horvath, Michael Jelenic',
                'cast'         => 'Chris Pratt, Anya Taylor-Joy, Charlie Day',
                'synopsis'     => 'The plot is still under development.',
                'duration'     =>  160,
                'language'     => 'ENG',
                'subtitles'    => 'BM',
                'age_rating'   => 'P12',
                'status'       => 'coming_soon',
                'release_date' => '2026-11-02',
                'image_path'   => 'ahyy3jYN98E7faQAN6MeZN9CBaCqMF7A916Q9brq.webp',
                'is_popular'   => false,
                'created_at'   => Carbon::now(),
                'updated_at'   => Carbon::now(),
            ],
            [
                'title'        => 'Freakier Friday',
                'genre'        => 'Comedy',
                'director'     => 'Nisha Ganatra',
                'cast'         => 'Julia Butters, Jamie Lee Curtis, Lindsay Lohan',
                'synopsis'     => 'Years after Tess and Anna endured an identity crisis, Anna now has a daughter and a soon-to-be stepdaughter. As they navigate the challenges that come when two families merge, Tess and Anna discover that lightning might strike twice.',
                'duration'     =>  111,
                'language'     => 'ENG',
                'subtitles'    => 'BM / CHI',
                'age_rating'   => 'P12',
                'status'       => 'now_showing',
                'release_date' => '2025-09-07',
                'image_path'   => 'tBMajTA8stQPAPqrRZtvAhCikygUAhapVRJmAQy3.png',
                'is_popular'   => false,
                'created_at'   => Carbon::now(),
                'updated_at'   => Carbon::now(),
            ],
            [
                'title'        => 'The Bad Guys 2',
                'genre'        => 'Animation',
                'director'     => 'Pierre Perifel, JP Sans',
                'cast'         => 'Anthony Ramos, Zazie Beetz, Sam Rockwell, Awkwafina, Craig Robinson, Marc Maron, Alex Borstein, Richard Ayoade, Lilly Singh',
                'synopsis'     => 'The Bad Guys are struggling to find trust and acceptance in their newly minted lives as Good Guys, when they are pulled out of retirement and forced to do "one last job" by an all-female squad of criminals.',
                'duration'     =>  104,
                'language'     => 'ENG',
                'subtitles'    => 'BM / CHI',
                'age_rating'   => 'P12',
                'status'       => 'now_showing',
                'release_date' => '2025-09-07',
                'image_path'   => 'HKniMVoiMCaQSAng3pbFUqjvuspyEPJJEVAXZxge.png',
                'is_popular'   => true,
                'created_at'   => Carbon::now(),
                'updated_at'   => Carbon::now(),
            ],
            [
                'title'        => 'The Way We Talk',
                'genre'        => 'Drama',
                'director'     => 'Adam Wong Sau-ping',
                'cast'         => 'Neo Yau, Chung Suet Ying, Marco Ng',
                'synopsis'     => 'Wolf, born into a Deaf family, embraces sign language with confidence despite obstacles in life; Sophie, having a cochlear implant at a young age, continuously strives to be seen as “normal”, despite struggling with oral language.',
                'duration'     =>  133,
                'language'     => 'CAN,SL',
                'subtitles'    => 'ENG / BM / CHI',
                'age_rating'   => '16',
                'status'       => 'archived',
                'release_date' => '2025-08-31',
                'image_path'   => 'W99GGu3AOtyCo862VXV8QueaZcAE9DzugDdFEM8H.png',
                'is_popular'   => false,
                'created_at'   => Carbon::now(),
                'updated_at'   => Carbon::now(),
            ],
            [
                'title'        => 'Omniscient Reader: The Prophecy',
                'genre'        => 'Fantasy',
                'director'     => 'Kim Byung-Woo',
                'cast'         => 'Ahn Hyo-Seop, Lee Min-Ho, Chae Soo-Bin, Nana, Jisoo, Shin Seung-Ho',
                'synopsis'     => 'Kim Dok Ja is an ordinary office worker and the sole devoted reader of the obscure fantasy web novel "Three Ways to Survive in a Ruined World". One day, reality shatters as the world transforms into the setting of the novel.',
                'duration'     =>  117,
                'language'     => 'KOR',
                'subtitles'    => 'BM / CHI / ENG',
                'age_rating'   => '13',
                'status'       => 'now_showing',
                'release_date' => '2025-08-31',
                'image_path'   => 'CU3Jowus4FaYd6urrqJvUamE2FJyewQHMgVzsPf3.png',
                'is_popular'   => true,
                'created_at'   => Carbon::now(),
                'updated_at'   => Carbon::now(),
            ],
            [
                'title'        => 'Smurfs',
                'genre'        => 'Animation',
                'director'     => 'Chris Miller',
                'cast'         => 'Rihanna, Nick Offerman, Natasha Lyonne, J.P. Karliak, Dan Levy, Amy Sedaris, Nick Kroll, James Corden, Kurt Russell, John Goodman',
                'synopsis'     => 'When Papa Smurf is mysteriously taken by evil wizards, Razamel and Gargamel, Smurfette leads the Smurfs on a mission into the real world to save him.',
                'duration'     =>  92,
                'language'     => 'ENG',
                'subtitles'    => 'BM / CHI',
                'age_rating'   => 'P12',
                'status'       => 'now_showing',
                'release_date' => '2025-09-17',
                'image_path'   => 'i2KKf5lqoJjArhRa2XeDmj4AlHinpMIleZsQzp2t.png',
                'is_popular'   => true,
                'created_at'   => Carbon::now(),
                'updated_at'   => Carbon::now(),
            ],
            [
                'title'        => "Doraemon the Movie: Nobita's Art World Tales",
                'genre'        => 'Animation',
                'director'     => 'Teramoto Yukiyo',
                'cast'         => 'Mizuta Wasabi, Ohara Megumi, Kakazu Yumi, Kimura Subaru, Seki Tomokazu',
                'synopsis'     => 'Nobita and friends enter a painting world using a secret gadget, uncovering a legend of “world destruction” while searching for the hidden jewel Artoria Blue.',
                'duration'     =>  105,
                'language'     => 'JPN',
                'subtitles'    => 'BM / CHI / ENG',
                'age_rating'   => 'U',
                'status'       => 'now_showing',
                'release_date' => '2025-09-17',
                'image_path'   => 'KdXRRMwrnD7tgAxALAXvPOclRSy0sJ1ydRLLj63x.png',
                'is_popular'   => true,
                'created_at'   => Carbon::now(),
                'updated_at'   => Carbon::now(),
            ],
            [
                'title'        => 'Follow Aunty La',
                'genre'        => 'Comedy',
                'director'     => 'Mayiduo',
                'cast'         => 'Regina Lim, Xixi Lim, Ma Yi Duo, Sai',
                'synopsis'     => 'A humble fishball seller seeks revenge on her cheating husband by trying to become a famous influencer.',
                'duration'     =>  129,
                'language'     => 'MAN',
                'subtitles'    => 'ENG',
                'age_rating'   => '13',
                'status'       => 're_released',
                'release_date' => '2025-08-31',
                'image_path'   => '9THPiF1HO9a9Y9Z4ODNFXcuhLFKfR2w0tVpe4jp8.webp',
                'is_popular'   => true,
                'created_at'   => Carbon::now(),
                'updated_at'   => Carbon::now(),
            ],
            [
                'title'        => 'The Lychee Road',
                'genre'        => 'Comedy',
                'director'     => 'Da Peng',
                'cast'         => 'Da Peng, Andy Lau, White K, Yang Mi, Sunny Sun, Zhuang Da Fei, Terrance Lau, Lam Suet, Zhang Ruo Yun',
                'synopsis'     => 'During the Tang Dynasty, a low-ranking official unexpectedly becomes the “Litchi Envoy”, leading to unexpected events.',
                'duration'     => 123,
                'language'     => 'MAN',
                'subtitles'    => 'ENG',
                'age_rating'   => '13',
                'status'       => 'now_showing',
                'release_date' => '2025-08-07',
                'image_path'   => 'F7QII320QBNI7Z57fOvBwKs327eouhx3YhKiadnq.webp',
                'is_popular'   => false,
                'created_at'   => Carbon::now(),
                'updated_at'   => Carbon::now(),
            ],
            [
                'title'        => 'Shaman',
                'genre'        => 'Horror',
                'director'     => 'Antonio Negret',
                'cast'         => 'Daniel Gillies, Sara Canning, Jett Klyne',
                'synopsis'     => 'A missionary in Ecuador must face her faith when her son is possessed by dark forces.',
                'duration'     =>  99,
                'language'     => 'ENG',
                'subtitles'    => 'BM / ENG',
                'age_rating'   => '18',
                'status'       => 'now_showing',
                'release_date' => '2025-08-07',
                'image_path'   => 'L9HVe1blfUzRCzCIwum0BZnkN9rmXcFrpvzbhBIe.png',
                'is_popular'   => true,
                'created_at'   => Carbon::now(),
                'updated_at'   => Carbon::now(),
            ],
            [
                'title'        => 'Thalapathy',
                'genre'        => 'Action',
                'director'     => '',
                'cast'         => '',
                'synopsis'     => '',
                'duration'     => 162,
                'language'     => 'TAM',
                'subtitles'    => 'ENG',
                'age_rating'   => '16',
                'status'       => 'coming_soon',
                'release_date' => '2025-11-28',
                'image_path'   => 'F2mlj6RXzsgKz4JlTPJF7QQ3CzVoUkwR55CKS9ET.png',
                'is_popular'   => false,
                'created_at'   => Carbon::now(),
                'updated_at'   => Carbon::now(),
            ],
            [
                'title'        => 'Together',
                'genre'        => 'Horror',
                'director'     => 'Michael Shanks',
                'cast'         => 'Dave Franco, Alison Brie, Damon Herriman',
                'synopsis'     => 'A couple’s relationship is tested by supernatural forces after moving to the country.',
                'duration'     =>  99,
                'language'     => 'ENG',
                'subtitles'    => 'BM',
                'age_rating'   => '18',
                'status'       => 'coming_soon',
                'release_date' => '2025-07-31',
                'image_path'   => 'AsWwlX1JU6qsTdGkX6nCF7tiJxrOzz8GZttuTW5c.webp',
                'is_popular'   => false,
                'created_at'   => Carbon::now(),
                'updated_at'   => Carbon::now(),
            ],
                        [
                'title'        => 'Baaghi 4',
                'genre'        => 'Action',
                'director'     => 'Michael Shanks',
                'cast'         => 'Dave Franco, Alison Brie, Damon Herriman',
                'synopsis'     => 'A couple’s relationship is tested by supernatural forces after moving to the country.',
                'duration'     =>  150,
                'language'     => 'ENG',
                'subtitles'    => 'ENG',
                'age_rating'   => '16',
                'status'       => 'now_showing',
                'release_date' => '2025-08-31',
                'image_path'   => 'rBuYnbkQIdnMBWb36akQvWA7c6Uo0VjEtNb26xUC.png',
                'is_popular'   => false,
                'created_at'   => Carbon::now(),
                'updated_at'   => Carbon::now(),
            ],
        ]);
    }
}
